
export const posts = [
  { 
  id:1, 
  image:'photo-article-01.png',
  title:'De Figma a CSS en un click con este plugin',
  avatar:'avatar-article-01.png',
  user:'Leonidas',
  time:'8 min read',
  },
  {
  id:2, 
  image:'photo-article-02.png',
  title:'Toma fotografías que luzcan profesionales con tu teléfono',
  avatar:'avatar-article-02.png',
  user:'Carlos',
  time:'6 min read',
  },
  {
  id:3, 
  image:'photo-article-03.png',
  title:'3 libros para comenzar en UX-UI',
  avatar:'avatar-article-01.png',
  user:'uxcristopher',
  time:'8 min read',
  },
  {
  id:4, 
  image:'photo-article-04.png',
  title:'Becas por estudiar',
  avatar:'avatar-article-04.png',
  user:'Humberto',
  time:'8 min read',
  },
   {
  id:5, 
  image:'photo-article-05.png',
  title:'Más que un color bonito',
  avatar:'avatar-article-05.png',
  user:'Sandra',
  time:'8 min read',
  },
  {
  id:6, 
  image:'photo-article-06.png',
  title:'El misterio de las APIs',
  avatar:'avatar-article-06.png',
  user:'Mafer Mazu',
  time:'8 min read',
  },
  {
  id:7, 
  image:'photo-article-07.png',
  title:'Hola Cypress',
  avatar:'avatar-article-07.png',
  user:'Miguel',
  time:'10 min read',
  },
  {
  id:8, 
  image:'photo-article-08.png',
  title:'Qué hay detrás de flex:1;',
  avatar:'avatar-article-08.png',
  user:'Leonidas',
  time:'6 min read',
  },
  {
  id:9, 
  image:'photo-article-09.png',
  title:'Desearás haber comenzado hoy',
  avatar:'avatar-article-09.png',
  user:'Humberto',
  time:'8 min read',
  }
];